### ISSUE TITLE
Should pass test `done` argument to `*async` transformer functions

### ISSUE THREAD

**Issue by tunnckoCore** [jstransformers/test-jstransformer#16]
Actually, just realized that `test-jstransformer` assume `*async` functions always return promise, but by default `jstransformer` allow passing `done` callback instead of returning promise.

E.g.

``` js
exports.renderFileAsync = function (fp, options, done) {
  if (typeof options === 'function') {
    done = options
    options = {}
  }
  sheetify(fp).bundle(options, done)
};
```

And `test-jstransformer` fails, because it waits `*Async` methods to only return promise.
This can be fixed if we pass [test done() function here](https://github.com/jstransformers/test-jstransformer/blob/master/index.js#L155), same for other `*async` transformer methods.

like below sample? i'm almost sure it won't work. 
That's why I invented hybrids - [hybridify](https://github.com/hybridables/hybridify) - which accept both callback and returning promise and notify both sides so users are able to do below thing, which in some cases like that can be useful.

``` js
if (transform.renderFileAsync) {
  test(transform.name + '.renderFileAsync()', function (done) {
    transform.renderFileAsync(inputFile, options, locals, done).then(function (output) {
      checkOutput(output);
    });
  });
}
```

I know that we can just wrap it in promise and also noticed that we mostly do it, but I don't see reason to do it and add more dependencies when `jstransformer` allows us to do it in old-school style callbacks.

**Comment by ForbesLindesay** [comment]
The external API exposed by `jstransformer` module supports an optional callback as the final argument.  The internal `jstransfomer` specification that is consumed by the `jstransformer` module requires that async methods always return promises.  This is intentional, and not a bug in test-jstransformer.  You should update your library to return promises from async methods.

**Comment by tunnckoCore** [comment]
There's no logic. We should be able to do it as in the example above. Because that's adding   `promise` module or `bluebird` or any other promise lib to the current transformer is unnecessary.

JSTransformer should handle that, instead to add dependencies to the transformers. In most cases transformers that we wrap is async.

**Comment by ForbesLindesay** [comment]
Using callbacks leads to bugs time and time again.  In the interests of ensuring that jstransformers is robust and stable, it will always use promises internally.  The `promise` module is a tiny dependency and not worth worrying about, and once node > 0.12 is ubiquitous you won't even need that because `Promise` will be available as a global.
