### ISSUE TITLE
CodeClimate report: code coverage, linting, code duplication

### ISSUE THREAD

**Issue by tunnckoCore** [jstransformers/test-jstransformer#2]
@ForbesLindesay firstly, Im very curious why you always use `else {}` in your code, where it is absolutely not needed?

All that and stuff leads to complex code, low coverage, low GPA, duplication and etc.

https://codeclimate.com/github/jstransformers/test-jstransformer
https://codeclimate.com/github/jstransformers/test-jstransformer/index.js

**Comment by RobLoach** [comment]
> firstly, Im very curious why you always use else {} in your code, where it is absolutely not needed?

Are you talking about the following code block?

``` javascript
    }
    if (gotResult) {
      return resolve(result);
    } else {
      throw new Error('Could not find a file matching ' + filename);
    }
  } else {
    return resolve(filename);
  }
```

If you provide a pull request, I'm sure it could be easily fixed.

> All that and stuff leads to complex code, low coverage, low GPA, duplication and etc.

And stuff?

> Complex code

Let's look at each complexity and then figure out what to do with it. Do you have any in mind?

> Low coverage

It's because the [`test-jstransformer` test case](https://github.com/jstransformers/test-jstransformer/blob/master/test/index.js) doesn't implement all the given functions. We need to add those functions in to raise test coverage.

**Comment by ForbesLindesay** [comment]
I'm not sure what explicit vs. implicit else blocks have to do with code coverage?  Or automated linting tools for that matter?

I sometimes think it's clearer.  e.g. I would do:

``` js
function foo(val) {
  if (!val) {
    // throw or return early
  }
  // the main
  // function
  // that is
  // executed
  // except for
  // some corner case
}
```

but I actually think:

``` js
function foo(val) {
  if (condition(val)) {
    return doThingA();
  } else {
    return doThingB();
  }
}
```

is clearer than:

``` js
function foo(val) {
  if (condition(val)) {
    return doThingA();
  }
  return doThingB();
}
```

because it is a better match for my mental model of that code.

**Comment by TimothyGu** [comment]
I don't see how `else`s contribute to the lower GPA on CodeClimate, but personally I prefer not using `else`s especially if the else block is long, on the basis of merely reducing indentation levels.

For duplication. CodeClimate reports a 3-line duplication and a 2-line duplication, that IMO doesn't worth it to be factored into a factory function. Interestingly, the real duplications (the catch clause with two `console.log`s, the `checkOutput`s) are not even considered duplications by CodeClimate, probably since those lines are not covered by the test suite.

Other two linting errors are trivial and can be fixed in an instant.
